#name: Landslide Detection

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Script
      run: python detect_landslide.py
